DIVISION_NAME = {"en": "Division name is required", "ch_ZN": "먼저 이름이 필요합니다"}
FIRST_NAME_REQUIRED = "First name is required."
LAST_NAME_REQUIRED = "Last name is required."
PHONE_NUMBER_REQUIRED = "Phone is required."
EMAIL_REQUIRED = "Email is required."
PHONE_NUMBER_VALIDATION = "Phone is invalid."
EMAIL_VALIDATION = "Email is not valid."
ENTER_REGISTERED_EMAIL = "Please enter your registered email ID"
PASSWORD_REQUIRED = "Please enter your password"
ENTER_VALID_EMAIL = "Please enter a valid email ID"
PASSWORD_CHARACTERS_VALIDATION = "Password has to be at least 8 characters"
PASSWORD_RESET_EMAIL_SENT_TEXT = "Password Reset Email Sent"
EMAIL_LINK_VALIDATION = (
    "We've sent you an email containing a link that will allow you to reset your password. Once you receive "
    "the email follow the instructions to change your password "
)
PASSWORD_MATCH_VALIDATION = "Passwords don't match"
Alert_MESSAGE = (
    "Your account has been locked. Please contact your system administrator."
)
HIGH_SCHOOL_SCORE_VALIDATION = "Your score must be less than 4."
BUDGET_FIELD_VALIDATION = "Budget range should be between 0 to 1,00,000"
STUD_PROFILE_FIRST_NAME = "ajamadar"
STUD_PROFILE_LAST_NAME = "student"
STUD_PROFILE_EMAIL = "ajamadar+automation01@ischoolconnect.com"
STUD_PROFILE_NUMBER = "023345728"
STUD_ADDRESS_MAX_CHAR = "rfGPUUDVCJHle3MftVDbbW5wfm8rBu7OEvXZO8P5dUtZ9m3FFH8rYBw6n3jyAU7RoxpJK58ojepTjVQ5vfwvXkU3fN3mYe0DrsJdJI275AIk7oUMMHt1XRfFX3U9SOBcLn75GfxSHNYaUsAXlal26hhseDZGhijC1CrjeoDBYcVntriMAUwMWyijztPDtz7GCPnxnrS0jxUE4UzUWYzIEz2voHdpwMYJyN8peUp4mbQFN1wTHHtmCAmdwnRnm0j5 "
STUD_PROFILE_STATE_NAME = "Maharashtra"
STUD_PROFILE_CITY_NAME = "Mumbai"
STUD_PROFILE_ZIPCODE = "123456"
STUD_REAL_ADDRESS = "Main Road, Mumbai"
ADVISOR_BASE_URL = "https://advisor-dashboard-release.ischoolconnect.com/"
MANAGE_USER_BASE_URL = "https://advisor-dashboard-release.ischoolconnect.com/dashboard/"
STUDENT_BASE_URL = "https://student-dashboard-release.ischoolconnect.com/dashboard"
INVALID_LOGIN = "Invalid"
INVALID_PASSWORD = "Invalid"
USER_FORM_FIRST_NAME = "First name is invalid"
USER_FORM_LAST_NAME = "Last name is required"
USER_FORM_EMAIL = "Email is required"
USER_FORM_PHONE_NUMBER = "Phone number is invalid"
USER_FORM_IDENTIFIER = "No spaces allowed"
CHANGE_ACCESS_LEVEL_ESSENTIAL = "Essential"
CHANGE_ACCESS_LEVEL_VIEW_ACCESS = "View Access"
NO_MATCH = "No Matching Results"
APPLY = "Apply"
APPLIED = "Applied"
ADD_TO_FAVORITES = "Add to Favorites"
ADDED_TO_FAVORITES = "Added to Favorites"
COMMISSION = "Commission"
INVALID_EMAIL = "Email is invalid"
GPA_EXAM_ERROR_MESSAGE = "Your score must be less than 4."
CGPA_EXAM_ERROR_MESSAGE = "Your score must be less than 10."
HIGH_SCHOOL_PERCENTAGE_ERROR_MESSAGE = "Your score must be less than 100."
SAT_APTITUDE_TEST_ERROR_MESSAGE = "Your score must be between 400 and 1600."
ACT_APTITUDE_TEST_ERROR_MESSAGE = "Your score must be between 1 and 36."
GRE_APTITUDE_TEST_ERROR_MESSAGE = "Your score must be between 260 and 340."
GMAT_APTITUDE_TEST_ERROR_MESSAGE = "Your score must be between 200 and 800."
IELTS_EXAM_ERROR_MESSAGE = "Your score must be less than 9."
TOEFL_EXAM_ERROR_MESSAGE = "Your score must be less than 120."
CAE_EXAM_ERROR_MESSAGE = "Your score must be between 80 and 230."
PIT_EXAM_ERROR_MESSAGE = "Your score must be between 10 and 90."
KITE_EXAM_ERROR_MESSAGE = "Your score must be less than 700."
DREAM_BUCKET = "Dream"
SAFE_BUCKET = "SAFE"

