from tests.recommendation_engine.view_recommendation.common.division import DivisionOwnerRecommendationsClass


class TestKaplanDivisionOwnerRecommendationsClass(DivisionOwnerRecommendationsClass):
    pass
