from tests.recommendation_engine.share_recommendation.common.advisor import AdvisorOwnerShareRecommendationsClass


class TestKaplanAdvisorOwnerShareRecommendationsClass(AdvisorOwnerShareRecommendationsClass):
    pass