from tests.browser_course.navigate_to_school_profile.common.advisor import AdvisorOwnerNavigateSchoolProfileClass


class TestOneEduDivisionOwnerNavigateToSchoolClass(AdvisorOwnerNavigateSchoolProfileClass):
    pass
