from tests.browser_course.navigate_to_school_profile.common.student import StudentNavigateSchoolProfileClass


class TestOneEduStudentNavigateToSchoolClass(StudentNavigateSchoolProfileClass):
    pass
