from tests.recommendation_engine.edit_recommendation.common.advisor import AdvisorOwnerEditRecommendationsClass


class TestKaplanAdvisorOwnerEditRecommendationsClass(AdvisorOwnerEditRecommendationsClass):
    pass