from tests.user_management.manage_division.add_and_update.common.account_owner import CreateAndUpdateDivisionOwnerClass


class TestOneEduCreateAndUpdateDivisionClass(CreateAndUpdateDivisionOwnerClass):
    pass
